apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-agent
  namespace: devops-tools
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-agent-server
  template:
    metadata:
      labels:
        app: jenkins-agent-server
    spec:
      containers:
        - name: jenkins-agent
          image: jenkins/ssh-agent:alpine
          resources:
            limits:
              memory: "5Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          env:
            - name: JENKINS_AGENT_SSH_PUBKEY
              value: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJXQF+30FVOC2aQQih0gGa6LkGWc+4qzVyQqV7NGiKct dillonmarquard@Issuus-MacBook-Pro-2.local
          ports:
            - name: tcp
              containerPort: 22